version: '3.8'
services:
  app-service:
    build: 
    context: ./app-service
    dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - STORAGE_SERVICE_URL=http://storage-service:8001
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

    depends_on:
      - database
  
  storage-service:
    build: 
    context: ./storage-service
    dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password