FROM python:3.11-bullseye

WORKDIR /app


COPY requirements.txt ./

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--port", "8000"]