FROM python:3.12-slim

WORKDIR /app


COPY requirements.txt ./

# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "run:server", "--port", "8001"]